GET http://localhost:3000/api/persons 

###
GET http://localhost:3000/api/persons/1

###
DELETE http://localhost:3000/api/persons/1

###
POST http://localhost:3000/api/persons
Content-Type: application/json

  {
    "name": "Johnny W",
    "number": "123456789"

  }

###
GET http://localhost:3000/info
